### ISSUE TITLE
Can't call module attribute or method from do block

### ISSUE THREAD

**Issue by dylan-chong** [KazuCocoa/ex_parametarized#12]
```elixir
  test_with_params "good", fn p -> p end, do: [{1}]
  @params [{1}]
  test_with_params "bad", fn p -> p end, do: @params
```

The bad tests throws this error:

```
(Protocol.UndefinedError) protocol Enumerable not implemented for {:@, [line: 12], [{:params, [line: 12], nil}]}. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) /private/tmp/elixir-20170801-16561-1c6hni3/elixir-1.5.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20170801-16561-1c6hni3/elixir-1.5.1/lib/elixir/lib/enum.ex:145: Enumerable.count/1
    (elixir) lib/enum.ex:497: Enum.count/1
    (ex_parameterized) lib/ex_parameterized/params.ex:54: ExUnit.Parameterized.Params.param_with_index/1
    (ex_parameterized) lib/ex_parameterized/params.ex:24: ExUnit.Parameterized.Params.do_test_with/3
    (ex_parameterized) expanding macro: ExUnit.Parameterized.Params.test_with_params/3
    test/kt_solver_test.exs:12: Part1KTSolverTest (module)
    (elixir) lib/code.ex:376: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

A second bad test throws a similar error:

```elixir
  def params2, do: [{1}]
  test_with_params "bad", fn p -> p end, do: params2
```

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:params2, [line: 12], nil}. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) /private/tmp/elixir-20170801-16561-1c6hni3/elixir-1.5.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20170801-16561-1c6hni3/elixir-1.5.1/lib/elixir/lib/enum.ex:145: Enumerable.count/1
    (elixir) lib/enum.ex:497: Enum.count/1
    (ex_parameterized) lib/ex_parameterized/params.ex:54: ExUnit.Parameterized.Params.param_with_index/1
    (ex_parameterized) lib/ex_parameterized/params.ex:24: ExUnit.Parameterized.Params.do_test_with/3
    (ex_parameterized) expanding macro: ExUnit.Parameterized.Params.test_with_params/3
    test/kt_solver_test.exs:12: Part1KTSolverTest (module)
    (elixir) lib/code.ex:376: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

My purpose for extracting the parameters out is because i want my tests to run on multiple modules that are very similar (I am testing different algorithms that each should output the same results). I don't want to have to copy paste the list of modules i want to test for each test.

**Comment by dylan-chong** [comment]
My current workaround for this is to create a new module above the test module, and in this new model create a method that returns the list of models that i want to test.

**Comment by KazuCocoa** [comment]
thanks.

Yeah, `@hoge` create special AST.

idea https://github.com/KazuCocoa/ex_parameterized/tree/fix_private_attribute

**Comment by KazuCocoa** [comment]
I've tried to fix this issue, but it looks difficult to manage correctly, and eventually, I've reverted _https://github.com/KazuCocoa/ex_parameterized/pull/17_

**Comment by dylan-chong** [comment]
I might have a play with this sometime
