### ISSUE TITLE
Cannot call aliased module inside do block

### ISSUE THREAD

**Issue by dylan-chong** [KazuCocoa/ex_parametarized#19]
```

defmodule Mod do
  @lily_default_octave 1
  def default_octave, do: @lily_default_octave
end

  alias Mod, as: M
  test_with_params "bad", fn arg -> arg end do
    v = M.default_octave()
    [
      {v},
      {v + 1},
    ]
  end
```

** (Protocol.UndefinedError) protocol Enumerable not implemented for {:__block__, [], [{:=, [line: 132], [{:v, [line: 132], nil}, {{:., [line: 132], [{:__aliases__, [counter: 0, line: 132], [:M]}, :default_octave]}, [line: 132], []}]}, [{:{}, [line: 134], [{:v, [line: 134], nil}]}, {:{}, [line: 135], [{:+, [line: 135], [{:v, [line: 135], nil}, 1]}]}]]}. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) /private/tmp/elixir-20171219-79248-1tthq3/elixir-1.5.3/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20171219-79248-1tthq3/elixir-1.5.3/lib/elixir/lib/enum.ex:145: Enumerable.count/1
    (elixir) lib/enum.ex:500: Enum.count/1
    lib/ex_parameterized/params.ex:54: ExUnit.Parameterized.Params.param_with_index/1
    lib/ex_parameterized/params.ex:24: ExUnit.Parameterized.Params.do_test_with/3
    expanding macro: ExUnit.Parameterized.Params.test_with_params/3
    test/ex_composer_bot/pitch_test.exs:131: ExComposerBotTest.Pitch (module)
    (elixir) lib/code.ex:376: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5

**Comment by KazuCocoa** [comment]
It looks same as https://github.com/KazuCocoa/ex_parameterized/issues/12#issuecomment-357715397 ...
